In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.7.0'

## Create Tensor

In [4]:
# Float Tensor with 3 rows and 2 columns
a = torch.FloatTensor(3, 2)
a

tensor([[-1.3338e+21,  4.5904e-41],
        [-1.3338e+21,  4.5904e-41],
        [-1.3358e+21,  4.5904e-41]])

### Inplace operations

In [5]:
# Replace zero in all positions of tensor
# _ is inplace operation in pytorch
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Constant Value

In [7]:
# Create fron constant value
torch.FloatTensor(
    [[1, 2, 3],
    [3, 2, 1]]
)

tensor([[1., 2., 3.],
        [3., 2., 1.]])

### Numpy

In [8]:
# Create from numpy
n = np.zeros(shape = (3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
# Put numpy array into stensor module
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

### Numpy with datatype

In [28]:
n = np.zeros(shape = (3, 2), dtype = np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [30]:
n = np.zeros(shape = (3,2))
torch.tensor(n, dtype = torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Scala Tensors
zero-dimensional tensors  = scalar values

In [31]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [32]:
s = a.sum()
s

tensor(6)

In [33]:
s.item()

6

In [38]:
torch.tensor(1)

tensor(1)

### Tensor Operations
Most of time, tensor operations are trying to correspond to their NumPy equivalent. <br/>
It here is some no-very-specialized function in NumPy, then there is function in Pytorch. <br/>
Ex. ```torch.stack()```, ```torch.transpose()```, ```torch.cat()```

- full reference http://pytorch.org/docs/